Test symfony (#9)

diff --git a/.github/workflows/backendCi.yml b/.github/workflows/backendCi.yml
--- a/.github/workflows/backendCi.yml
+++ b/.github/workflows/backendCi.yml
@@ -59,3 +59,65 @@ jobs:
           if [[ ! -z "${{ steps.changes.outputs.changedFiles }}" ]]
             then php bin/phpstan analyse ${{ steps.changes.outputs.changedFiles }}
           fi
+  build-tests:
+    name: Unit & Functional Tests
+    runs-on: ubuntu-latest
+    container: node:latest
+    services:
+      mariadb:
+        image: mariadb:latest
+        env:
+          MYSQL_ROOT_PASSWORD: ${{ MYSQL_ROOT_PASSWORD }}
+          MYSQL_USER: ${{ MYSQL_USER }}
+          MYSQL_PASSWORD: ${{ MYSQL_PASSWORD }}
+          MYSQL_DATABASE: ${{ MYSQL_DATABASE }}
+        ports:
+          - 3306:3306
+    steps:
+      - name: Git Checkout
+        uses: actions/checkout@v3
+      - name: Setup PHP
+        uses: shivammathur/setup-php@master
+        with:
+          php-version: 8.3
+          coverage: xdebug
+          ini-values: memory_limit=-1
+          extensions: imagick, bcmath, mysqli, intl, pdo_mysql, pdo_pgsql, pgsql, opcache, gd, xsl, zip, soap, pcntl, sockets, gettext, xdebug
+      - name: Composer install
+        uses: ramsey/composer-install@v2
+        with:
+          composer-options: --profile --ignore-platform-reqs
+      - name: Setup MariaDB
+        run: |
+          apt-get update
+          apt-get install --yes mariadb-client
+      - name: Create Database
+        run: |
+          php bin/console doctrine:database:create --env=test
+          php bin/console doctrine:schema:update --env=test --force --complete || echo "No migrations found or schema update failed"
+      - name: Install Assets
+        run: |
+          yarn install --force
+          yarn encore dev
+      - name: PHPUnit Tests
+        run: php bin/phpunit tests/ --configuration phpunit.xml --coverage-cobertura ./coverage.xml
+        env:
+          XDEBUG_MODE: coverage
+      - name: Code Coverage Analysis
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: coverage.xml
+          badge: true
+          fail_below_min: false
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 80'
+      - name: Add Coverage Summary
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: github.event_name == 'pull_request'
+        with:
+          recreate: true
+          path: code-coverage-results.md
